version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gwz_sales
        description: sales of greenweez
        columns:
          - name: date_date
          - name: orders_id
          - name: pdt_id
          - name: revenue
          - name: quantity
      - name: product
        identifier: raw_gz_product
        description: liste des porduits greenweez
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null
          - name: purchSE-PRICE
      - name: ship
        identifier: raw_gz_ship
        description: informations de shipping greenweez
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null  
          - name: shipping_fee
          - name: shipping_fee_1
          - name: logCost
          - name: ship_cost
